// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "trix"
import "@rails/actiontext"
import "jquery"
import "jquery_ujs"
import "popper"
import "bootstrap"
import "vendor/custom"
import "vendor/owl"
import "vendor/slick"
import "vendor/isotope"
import "vendor/accordions"
